#yaml, yml 포맷(규칙))
#key와 value 사이에 스페이스 한칸을 띄워야 함.
#-(하이픈)을 통해서 Array임을 알수가 있습니다.
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: 3075

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #use-new-id-generator-mappings: false #deprecated
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false